Started logging messages at Thu Jul 16 11:43:12 2015
Info:    Using UV tolerance 1e-006
Info:    Using UV tolerance 1e-006
Info:    HwNlibToTSLib options selected:
Info:        Points: Off
Info:        Curves: On
Info:        Surfaces: Off
Info:        BReps: On
Info:        Do not create IwAssembly/IwAssemblyInstance objects
Info:        Making untrimmed surfaces into BReps
Info:        Making solids into single BReps
Info:        Make components of failed trims
Info:        Make faces of failed B-reps
Info:    HW SAT v1.2.6-maint
Info:    Reading 
Info:    Processing 
Info:    Transferring 
Info:    
Info:    Found 0 points in file
Info:    Found 0 curves in file
Info:    Found 0 surfaces in file
Info:    Found 0 trimmed surfaces in file
Info:    Found 1 B-reps in file
Info:    Found 17 B-rep faces in file
Info:    
Info:    Using 3D tolerance 1e-006
Info:    Working on 0
Info:        Working on 37
Info:            Created 
Info:        Working on 58
Info:            Created 
Info:        Working on 6
Info:            Created 
Info:        Working on 9
Info:            Created 
Info:        Working on 89
Info:            Created 
Info:        Working on 90
Info:            Created 
Info:        Working on 117
Info:            Created 
Info:        Working on 119
Info:            Created 
Info:        Working on 14
Info:            Created 
Info:        Working on 112
Info:            Created 
Info:        Working on 113
Info:            Created 
Info:        Working on 20
Info:            Created 
Info:        Working on 143
Info:            Created 
Info:        Working on 185
Info:            Created 
Info:        Working on 28
Info:            Created 
Info:        Working on 183
Info:            Created 
Info:        Working on 214
Info:            Created 
Info:        Working on 40
Info:            Created 
Info:        Working on 215
Info:            Created 
Info:        Working on 225
Info:            Created 
Info:        Working on 61
Info:            Created 
Info:        Working on 200
Info:            Created 
Info:        Working on 162
Info:            Created 
Info:        Working on 95
Info:            Created 
Info:        Working on 131
Info:            Created 
Info:        Working on 204
Info:            Created 
Info:        Working on 167
Info:            Created 
Info:        Working on 92
Info:            Created 
Info:        Working on 192
Info:            Created 
Info:        Working on 130
Info:            Created 
Info:        Working on 190
Info:            Created 
Info:        Working on 169
Info:            Created 
Info:        Working on 238
Info:            Created 
Info:        Working on 206
Info:            Created 
Info:        Working on 244
Info:            Created 
Info:        Working on 233
Info:            Created 
Info:        Working on 243
Info:            Created 
Info:        Working on 237
Info:            Created 
Info:        Working on 241
Info:            Created 
Info:        Working on 232
Info:            Created 
Info:        Created 
Info:    Working on BRep 0
Info:        Using 3D tolerance 0.000254275
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Finished with 
Info:    Points:                 0 found       0 created       0 failed
Info:    Coordinate Systems      0 found       0 created       0 failed
Info:    Curves:                 0 found       0 created       0 failed
Info:    Surfaces:               0 found       0 created       0 failed
Info:    Trimmed Surfaces:       0 found       0 created       0 failed
Info:    Breps:                  1 found       1 created       0 failed
Finished logging messages at Thu Jul 16 11:43:12 2015
