Started logging messages at Tue Jul 14 14:49:28 2015
Info:    Using UV tolerance 1e-006
Info:    Using UV tolerance 1e-006
Info:    HwNlibToTSLib options selected:
Info:        Points: Off
Info:        Curves: On
Info:        Surfaces: Off
Info:        BReps: On
Info:        Do not create IwAssembly/IwAssemblyInstance objects
Info:        Making untrimmed surfaces into BReps
Info:        Making solids into single BReps
Info:        Make components of failed trims
Info:        Make faces of failed B-reps
Info:    HW SAT v1.2.6-maint
Info:    Reading 
Info:    Processing 
Info:    Transferring 
Info:    
Info:    Found 0 points in file
Info:    Found 0 curves in file
Info:    Found 0 surfaces in file
Info:    Found 0 trimmed surfaces in file
Info:    Found 1 B-reps in file
Info:    Found 8 B-rep faces in file
Info:    
Info:    Using 3D tolerance 1e-006
Info:    Working on 0
Info:        Working on 60
Info:            Created 
Info:        Working on 61
Info:            Created 
Info:        Working on 82
Info:            Created 
Info:        Working on 83
Info:            Created 
Info:        Working on 6
Info:            Created 
Info:        Working on 76
Info:            Created 
Info:        Working on 101
Info:            Created 
Info:        Working on 9
Info:            Created 
Info:        Working on 99
Info:            Created 
Info:        Working on 116
Info:            Created 
Info:        Working on 13
Info:            Created 
Info:        Working on 114
Info:            Created 
Info:        Working on 121
Info:            Created 
Info:        Working on 21
Info:            Created 
Info:        Working on 107
Info:            Created 
Info:        Working on 119
Info:            Created 
Info:        Working on 38
Info:            Created 
Info:        Working on 62
Info:            Created 
Info:        Working on 88
Info:            Created 
Info:        Working on 108
Info:            Created 
Info:        Created 
Info:    Working on BRep 0
Info:        Using 3D tolerance 0.00080793
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Finished with 
Info:    Points:                 0 found       0 created       0 failed
Info:    Coordinate Systems      0 found       0 created       0 failed
Info:    Curves:                 0 found       0 created       0 failed
Info:    Surfaces:               0 found       0 created       0 failed
Info:    Trimmed Surfaces:       0 found       0 created       0 failed
Info:    Breps:                  1 found       1 created       0 failed
Finished logging messages at Tue Jul 14 14:49:28 2015
