Started logging messages at Tue Jul 14 12:42:55 2015
Info:    Using UV tolerance 1e-006
Info:    Using UV tolerance 1e-006
Info:    HwNlibToTSLib options selected:
Info:        Points: Off
Info:        Curves: On
Info:        Surfaces: Off
Info:        BReps: On
Info:        Do not create IwAssembly/IwAssemblyInstance objects
Info:        Making untrimmed surfaces into BReps
Info:        Making solids into single BReps
Info:        Make components of failed trims
Info:        Make faces of failed B-reps
Info:    HW SAT v1.2.6-maint
Info:    Reading 
Info:    Processing 
Info:    Transferring 
Info:    
Info:    Found 0 points in file
Info:    Found 0 curves in file
Info:    Found 0 surfaces in file
Info:    Found 0 trimmed surfaces in file
Info:    Found 1 B-reps in file
Info:    Found 31 B-rep faces in file
Info:    
Info:    Using 3D tolerance 1e-006
Info:    Working on 0
Info:        Working on 62
Info:            Created 
Info:        Working on 93
Info:            Created 
Info:        Working on 9
Info:            Created 
Info:        Working on 15
Info:            Created 
Info:        Working on 133
Info:            Created 
Info:        Working on 135
Info:            Created 
Info:        Working on 25
Info:            Created 
Info:        Working on 175
Info:            Created 
Info:        Working on 37
Info:            Created 
Info:        Working on 254
Info:            Created 
Info:        Working on 303
Info:            Created 
Info:        Working on 53
Info:            Created 
Info:        Working on 305
Info:            Created 
Info:        Working on 253
Info:            Created 
Info:        Working on 77
Info:            Created 
Info:        Working on 418
Info:            Created 
Info:        Working on 378
Info:            Created 
Info:        Working on 114
Info:            Created 
Info:        Working on 306
Info:            Created 
Info:        Working on 165
Info:            Created 
Info:        Working on 255
Info:            Created 
Info:        Working on 372
Info:            Created 
Info:        Working on 375
Info:            Created 
Info:        Working on 228
Info:            Created 
Info:        Working on 385
Info:            Created 
Info:        Working on 299
Info:            Created 
Info:        Working on 424
Info:            Created 
Info:        Working on 322
Info:            Created 
Info:        Working on 443
Info:            Created 
Info:        Working on 380
Info:            Created 
Info:        Working on 426
Info:            Created 
Info:        Working on 425
Info:            Created 
Info:        Working on 138
Info:            Created 
Info:        Working on 194
Info:            Created 
Info:        Working on 74
Info:            Created 
Info:        Working on 111
Info:            Created 
Info:        Working on 12
Info:            Created 
Info:        Working on 20
Info:            Created 
Info:        Working on 157
Info:            Created 
Info:        Working on 159
Info:            Created 
Info:        Working on 31
Info:            Created 
Info:        Working on 207
Info:            Created 
Info:        Working on 45
Info:            Created 
Info:        Working on 288
Info:            Created 
Info:        Working on 334
Info:            Created 
Info:        Working on 65
Info:            Created 
Info:        Working on 96
Info:            Created 
Info:        Working on 289
Info:            Created 
Info:        Working on 400
Info:            Created 
Info:        Working on 403
Info:            Created 
Info:        Working on 347
Info:            Created 
Info:        Working on 141
Info:            Created 
Info:        Working on 358
Info:            Created 
Info:        Working on 196
Info:            Created 
Info:        Working on 414
Info:            Created 
Info:        Working on 441
Info:            Created 
Info:        Working on 162
Info:            Created 
Info:        Working on 336
Info:            Created 
Info:        Working on 226
Info:            Created 
Info:        Working on 446
Info:            Created 
Info:        Working on 438
Info:            Created 
Info:        Working on 298
Info:            Created 
Info:        Working on 409
Info:            Created 
Info:        Working on 359
Info:            Created 
Info:        Working on 431
Info:            Created 
Info:        Working on 408
Info:            Created 
Info:        Working on 394
Info:            Created 
Info:        Working on 433
Info:            Created 
Info:        Working on 444
Info:            Created 
Info:        Created 
Info:    Working on BRep 1 (0)
Info:        Using 3D tolerance 0.000152833
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Working on BRep 2 (0)
Info:        Using 3D tolerance 0.000218332
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Finished with 
Info:    Points:                 0 found       0 created       0 failed
Info:    Coordinate Systems      0 found       0 created       0 failed
Info:    Curves:                 0 found       0 created       0 failed
Info:    Surfaces:               0 found       0 created       0 failed
Info:    Trimmed Surfaces:       0 found       0 created       0 failed
Info:    Breps:                  2 found       2 created       0 failed
Finished logging messages at Tue Jul 14 12:42:56 2015
